Power ups ly
COMP2522/project-yumo-john-lucas-viet pull request #10
Opened 2023-03-26 07:54 UTC by LucasHYing

PowerUpsObj class created

2023-03-26 16:44 UTC, John2T requested changes
Looks good to me, maybe change spawnPowerup to only be called when destroying an enemy though. Also any reason for GameObj to know be abstract?

2023-03-26 17:30 UTC, LucasHYing commented
I can't really find where the codes are when enemies are destroyed.

2023-03-26 22:22 UTC, John2T approved these changes

2023-03-27 00:03 UTC, John2T commented
Looks good to me, merging.

2023-03-27 00:03 UTC, merged